export const MESSAGE_TYPES = {
  NEW_JOB: 'NEW_JOB',
  ACTIVE_JOB: 'ACTIVE_JOB',
  INITIAL_JOBS: 'INITIAL_JOBS',
  JOB_UPDATED: 'JOB_UPDATED',
  JOB_REMOVED: 'JOB_REMOVED',
  JOB_ACCEPTED: 'JOB_ACCEPTED',
  JOB_COMPLETED: 'JOB_COMPLETED',
  PAYOUT_RECEIVED: 'PAYOUT_RECEIVED',
  NEW_RATING: 'NEW_RATING',
} as const;

export type NotificationType = typeof MESSAGE_TYPES[keyof typeof MESSAGE_TYPES];